# MOWBOT ROS Parameters - YAML Format
#
# Axis orientation: Z up, X fwd, Y left
# Ego (rover) origin: centre of mass 
#
# Hardware highlights:
#   Tracking camera, Intel Realsense T265
#   Compute, NVidia Jetson Tx1
#   Lidar, A2 Lidar 
#   Motor, TRAXXAS Velinion 3500
#   Chassis, TRAXXAS Slash 4x4

# VESC Motor controller parameters
vesc_driver_node:
  port: "/dev/ttyACM0" # Serial port of VESC, see /sys/class/tty/ttyA*

_min: 0.0 # VESC driver min, duty cycle 0..1
_max: 0.5 # VESC driver max, duty cycle 0..1

speed_to_erpm_gain: 4449.0 # MOWBOT Calibration
speed_to_erpm_offset: 0.0 # MOWBOT Calibration

kv: 3500 # rpm/v, Traxxas Velinion 3500 BLDC

# SERVO Steering parameters
steering_angle_to_servo_gain: -0.7645 # MOWBOT Calibration
steering_angle_to_servo_offset: 0.490 # MOWBOT Calibration

# MOWBOT Rover parameters
l_wheelbase: 0.324 # m,  MOWBOT Calibration
l_track: 0.18 # m, 
m_rover: 7.1 # kg, 
I_inertia_z: 69.0 # m^4, 
r_driveratio: 11.82 # unitless, overall reduction motor to wheels
k_spinloss: 0.001 # Nm/rpm_axle, drivetrain losses
l_wheel: 0.109 # m, tire diameter
l_dist_per_rev: 0.342 # m, meters per revolution
r_meter_per_tachtick: 0.00225 # m, meters per tach tick of drive motor


# TRACKING Camera parameters, intel T265
track_dx: 0.10 # m, motor offset from rover origin
track_dy: 0.0 # m, motor offset from rover origin
track_dz: 0.10 # m, motor offset from roer origin
track_fov: 163 # deg, camera field of view
track_resx: 848 # pixels, x
track_resy: 800 # pixels, y
track_binocsep: 0.064 # m, separation between imagers
track_rotation_x: -90 # deg, camera to rover
track_rotation_z: 180 # deg, camera to rover
track_rotation_y: 180 #deg, camera to rover
track_transform_x: [0.0, 0.0, -1.0] # transform x,y,z, realsense to rover coord
track_transform_y: [-1.0, 0.0, 0.0] # transform x,y,z, realsense to rover coord
track_transform_z: [0.0, 1.0, 0.0] # transform x,y,z, realsense to rover coord

# LIDAR Camera parameters, A2 Lidar
lidar_port: "/dev/ttyUSB0"
lidar_baud: "115200"
lidar_dx: 0.15 # m, lidar offset from rover origin
lidar_dy: 0.00 # m, lidar offset from rover origin
lidar_dz: 0.05 # m, lidar offset from rover origin

# GAMEPAD Teleoperation parameters, Logitech F710 
#    Help utility: 
#      sudo apt-get install jstest-gtk
#      jstest /dev/input/js1 (your port may vary)
#    
#    below button asignment given selector switch on gamepad set to "D" (not "X")
#    biggest difference with "X" mode - lt & rt become progressive, not on/off buttons
#    
#    button  description
#    0       x,blue
#    1       a,green
#    2       b,red
#    3       y,yellow
#    4       lb
#    5       rb
#    6       lt
#    7       rt
#    8       back
#    9       start
#    
#    base axes:             joy_node axes:  description:
#    0_ -32767 L, 32767 R   4_ 1 L, -1 R    directional pad
#    1_ -32767 U, 32767 D   5_ 1 U, -1 D    directional pad
#    2_ -32767 L, 32767 R   2_ 1 L, -1 R    right joystick 
#    3_ -32767 U, 32767 D   3_ 1 U, -1 D    right joystick 
#    4_ -32767 L, 32767 R   0_ 1 L, -1 R    left joystick  
#    5_ -32767 U, 32767 D   1_ 1 U, -1 D    left joystick  
#    
#    Node layout:
#    joy_node    - base ROS driver interface with controller
#                - detect button pressess / joystick positions
#                - populate "joy" topic
#                  - field, axis[6] float
#                  - field, buttons[12] float
#    teleop_logi - logic assigning button pushes to controller actions
#                - subscribe "joy" topic
#                - pulish "teleop_cmd" topic
#    
#    Logical assignment:
#      teleop_logi node
#      (default)       : no action mode, nothing pressed, motor commanded to zero
#      lb              : tele_dedman_btn : teleop mode, deadman switch, when held user uses gamepad for steering / throttle
#      left joystick   : tele_steer_ax   : teleop mode, steering L/R
#      right joystick  : tele_throt_ax   : teleop mode, throttle U
#      rb              : av_dedman_btn   : autonomous mode, deadman switch, must be held to avoid no action mode
#      start           : av_start_btn    : autonomous mode, signals logic to honor av steering / throttle commands
#      back            : av_pause_btn    : autonomous mode, signals logic to stop honoring av steering / throttle commands
#      x,blue          : av_throtup_btn  : autonomous mode, signals logic to step up throttle command
#      a,green         : av_throtdn_btn  : autonomous mode, signals logic to step down throttle command
#      y,yellow        : ros_start_btn   : autonomous mode, signals logic to record ROS Bag
#      b,red           : ros_stop_btn    : autonomous mode, signals logic to stop recording ROS Bag
teleop_logi:
  tele_dedman_btn: 4
  tele_steer_ax: 0
  tele_throt_ax: 3
  av_dedman_btn: 5
  av_start_btn: 9
  av_pause_btn: 8
  av_throtup_btn: 0
  av_throtdn_btn: 1
  av_manthrot_btn: 6
  ros_start_btn: 3
  ros_stop_btn: 2
  AV_THROT_NC: 0
  AV_THROT_INC: 1
  AV_THROT_DEC: 2
  AV_THROT_MAN: 3